import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'quickstart',
    'getting-started',
    'first-turn',
    'tutorial',
    'cli',
    {
      type: 'category',
      label: 'Release Notes',
      items: [
        'releases/v2-29-0',
        'releases/v2-28-0',
        'releases/v2-27-0',
        'releases/v2-26-0',
        'releases/v2-25-2',
        'releases/v2-25-1',
        'releases/v2-25-0',
        'releases/v2-24-3',
        'releases/v2-24-2',
        'releases/v2-24-1',
        'releases/v2-23-0',
        'releases/v2-22-0',
        'releases/v2-21-0',
        'releases/v2-20-0',
        'releases/v2-19-0',
        'releases/v2-18-0',
        'releases/v2-17-0',
        'releases/v2-16-0',
        'releases/v2-15-0',
        'releases/v2-14-0',
        'releases/v2-13-0',
        'releases/v2-12-0',
        'releases/v2-11-0',
      ],
    },
    'export-schema',
    'governance-report',
    'templates',
    {
      type: 'category',
      label: 'Protocol',
      items: [
        'protocol',
        'protocol-reference',
        'runner-interface',
        'build-your-own-runner',
        'protocol-implementor-guide',
        'remote-verification',
      ],
    },
    {
      type: 'category',
      label: 'Continuous Delivery',
      items: [
        'continuous-delivery-intake',
        'multi-repo',
      ],
    },
    'adapters',
    'plugins',
    'notifications',
    'recovery',
    'multi-session',
  ],
};

export default sidebars;
