import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'quickstart',
    'getting-started',
    'first-turn',
    'tutorial',
    'cli',
    {
      type: 'category',
      label: 'Release Notes',
      items: [
        'releases/v2-70-0',
        'releases/v2-69-0',
        'releases/v2-68-0',
        'releases/v2-67-0',
        'releases/v2-66-1',
        'releases/v2-66-0',
        'releases/v2-65-0',
        'releases/v2-64-0',
        'releases/v2-63-0',
        'releases/v2-62-0',
        'releases/v2-61-0',
        'releases/v2-60-0',
        'releases/v2-59-0',
        'releases/v2-58-0',
        'releases/v2-57-0',
        'releases/v2-56-0',
        'releases/v2-55-0',
        'releases/v2-54-0',
        'releases/v2-53-0',
        'releases/v2-52-0',
        'releases/v2-51-0',
        'releases/v2-50-0',
        'releases/v2-49-0',
        'releases/v2-48-0',
        'releases/v2-47-0',
        'releases/v2-46-2',
        'releases/v2-46-0',
        'releases/v2-45-0',
        'releases/v2-44-0',
        'releases/v2-43-0',
        'releases/v2-42-0',
        'releases/v2-41-0',
        'releases/v2-40-0',
        'releases/v2-39-0',
        'releases/v2-38-0',
        'releases/v2-37-0',
        'releases/v2-36-0',
        'releases/v2-35-0',
        'releases/v2-34-2',
        'releases/v2-33-1',
        'releases/v2-32-0',
        'releases/v2-31-0',
        'releases/v2-30-0',
        'releases/v2-29-0',
        'releases/v2-28-0',
        'releases/v2-27-0',
        'releases/v2-26-0',
        'releases/v2-25-2',
        'releases/v2-25-1',
        'releases/v2-25-0',
        'releases/v2-24-3',
        'releases/v2-24-2',
        'releases/v2-24-1',
        'releases/v2-23-0',
        'releases/v2-22-0',
        'releases/v2-21-0',
        'releases/v2-20-0',
        'releases/v2-19-0',
        'releases/v2-18-0',
        'releases/v2-17-0',
        'releases/v2-16-0',
        'releases/v2-15-0',
        'releases/v2-14-0',
        'releases/v2-13-0',
        'releases/v2-12-0',
        'releases/v2-11-0',
      ],
    },
    'export-schema',
    'governance-report',
    'policies',
    'approval-policy',
    'timeouts',
    'templates',
    {
      type: 'category',
      label: 'Examples',
      items: [
        'examples',
        'examples/governed-todo-app',
        'examples/habit-board',
        'examples/trail-meals-mobile',
        'examples/async-standup-bot',
        'examples/decision-log-linter',
        'examples/schema-guard',
        'examples/ci-runner-proof',
        'examples/external-runner-starter',
        'examples/live-governed-proof',
        'examples/mcp-echo-agent',
        'examples/mcp-http-echo-agent',
        'examples/mcp-anthropic-agent',
        'examples/remote-agent-bridge',
        'examples/remote-conformance-server',
      ],
    },
    {
      type: 'category',
      label: 'Protocol',
      items: [
        'protocol',
        'protocol-reference',
        'runner-interface',
        'build-your-own-runner',
        'protocol-implementor-guide',
        'remote-verification',
      ],
    },
    {
      type: 'category',
      label: 'Continuous Delivery',
      items: [
        'continuous-delivery-intake',
        'multi-repo',
      ],
    },
    {
      type: 'category',
      label: 'Integration',
      items: [
        'integration-guide',
        'adapters',
        'build-your-own-connector',
      ],
    },
    'plugins',
    'notifications',
    'recovery',
    'multi-session',
  ],
};

export default sidebars;
