/**
 * agentxchain restart — governed-only command.
 *
 * Reconstructs dispatch context from durable checkpoint state and assigns the
 * next turn. Unlike `resume` (which assumes the caller has session context),
 * `restart` assumes the caller has NO session context and rebuilds everything
 * from .agentxchain/session.json + .agentxchain/state.json.
 *
 * Use case: terminal died mid-run, machine restarted, new agent session
 * picking up a long-horizon governed run.
 */

import chalk from 'chalk';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { loadProjectContext } from '../lib/config.js';
import {
  assignGovernedTurn,
  getActiveTurns,
  getActiveTurnCount,
  reactivateGovernedRun,
  detectStateBundleDesync,
  STATE_PATH,
  HISTORY_PATH,
  LEDGER_PATH,
} from '../lib/governed-state.js';
import { writeDispatchBundle } from '../lib/dispatch-bundle.js';
import { getDispatchTurnDir } from '../lib/turn-paths.js';
import { consumeNextApprovedIntent } from '../lib/intake.js';
import { loadProjectState } from '../lib/config.js';
import { deriveRecoveryDescriptor } from '../lib/blocked-state.js';
import { deriveRecommendedContinuityAction } from '../lib/continuity-status.js';
import { readSessionCheckpoint, writeSessionCheckpoint, captureBaselineRef, SESSION_PATH } from '../lib/session-checkpoint.js';

/**
 * Generate a session recovery report summarizing the run state
 * so a new agent session can orient quickly.
 */
function generateRecoveryReport(root, state, checkpoint, driftWarnings = []) {
  const continuityAction = deriveRecommendedContinuityAction(state);
  const lines = [
    '# Session Recovery Report',
    '',
    `> Auto-generated by \`agentxchain restart\` at ${new Date().toISOString()}`,
    '',
    '## Run Identity',
    '',
    `- **Run ID**: \`${state.run_id}\``,
    `- **Project**: \`${state.project_id || 'unknown'}\``,
    `- **Status**: ${state.status}`,
    `- **Phase**: ${state.phase || state.current_phase || 'unknown'}`,
    '',
  ];

  if (checkpoint) {
    lines.push(
      '## Last Checkpoint',
      '',
      `- **Session**: \`${checkpoint.session_id}\``,
      `- **Last turn**: \`${checkpoint.last_turn_id || 'none'}\``,
      `- **Last role**: ${checkpoint.last_role || 'unknown'}`,
      `- **Reason**: ${checkpoint.checkpoint_reason}`,
      `- **Time**: ${checkpoint.last_checkpoint_at}`,
      '',
    );
  }

  // Recent decisions from ledger
  const ledgerPath = join(root, LEDGER_PATH);
  if (existsSync(ledgerPath)) {
    try {
      const entries = readFileSync(ledgerPath, 'utf8')
        .trim()
        .split('\n')
        .filter(Boolean)
        .map(l => JSON.parse(l));
      const recent = entries.slice(-5);
      if (recent.length > 0) {
        lines.push('## Recent Decisions', '');
        for (const entry of recent) {
          lines.push(`- \`${entry.decision_id || entry.id || 'unknown'}\`: ${entry.summary || entry.description || JSON.stringify(entry).slice(0, 100)}`);
        }
        lines.push('');
      }
    } catch {
      // Non-fatal
    }
  }

  // Turn history summary
  const historyPath = join(root, HISTORY_PATH);
  if (existsSync(historyPath)) {
    try {
      const entries = readFileSync(historyPath, 'utf8')
        .trim()
        .split('\n')
        .filter(Boolean)
        .map(l => JSON.parse(l));
      lines.push(`## Turn History`, '', `Total turns completed: ${entries.length}`, '');
      const recent = entries.slice(-3);
      if (recent.length > 0) {
        lines.push('### Last 3 Turns', '');
        for (const entry of recent) {
          lines.push(`- **${entry.turn_id}** (${entry.role}, phase: ${entry.phase}): ${entry.status}`);
        }
        lines.push('');
      }
    } catch {
      // Non-fatal
    }
  }

  // Pending gate / run completion surfacing
  if (state.pending_phase_transition) {
    const pt = state.pending_phase_transition;
    lines.push(
      '## Pending Phase Transition',
      '',
      `- **From**: ${pt.from}`,
      `- **To**: ${pt.to}`,
      `- **Gate**: ${pt.gate}`,
      `- **Requested by**: ${pt.requested_by_turn || 'unknown'}`,
      `- **Action**: Run \`${continuityAction.recommended_command}\` to continue`,
      '',
    );
  }

  if (state.pending_run_completion) {
    const pc = state.pending_run_completion;
    lines.push(
      '## Pending Run Completion',
      '',
      `- **Gate**: ${pc.gate}`,
      `- **Requested by**: ${pc.requested_by_turn || 'unknown'}`,
      `- **Action**: Run \`${continuityAction.recommended_command}\` to continue`,
      '',
    );
  }

  // Repo-drift warnings
  if (checkpoint?.baseline_ref && driftWarnings?.length > 0) {
    lines.push('## Continuity Warnings', '');
    for (const warning of driftWarnings) {
      lines.push(`- ⚠ ${warning}`);
    }
    lines.push('');
  }

  lines.push('## Next Steps', '');
  if (continuityAction.recommended_command && !continuityAction.restart_recommended) {
    const detail = continuityAction.recommended_detail ? ` Detail: ${continuityAction.recommended_detail}.` : '';
    lines.push(`Run \`${continuityAction.recommended_command}\` next.${detail}`, '');
  } else {
    lines.push('The next turn has been assigned. Check the dispatch bundle for context.', '');
  }

  return lines.join('\n');
}

export async function restartCommand(opts) {
  const context = loadProjectContext();
  if (!context) {
    console.log(chalk.red('No agentxchain.json found. Run `agentxchain init` first.'));
    process.exit(1);
  }

  const { root, config } = context;

  if (config.protocol_mode !== 'governed') {
    console.log(chalk.red('The restart command is only available for governed projects.'));
    process.exit(1);
  }

  // Load state
  const statePath = join(root, STATE_PATH);
  if (!existsSync(statePath)) {
    console.log(chalk.red('No governed run found. Use `agentxchain run` to start a governed run.'));
    process.exit(1);
  }

  const state = JSON.parse(readFileSync(statePath, 'utf8'));

  // Load checkpoint (optional — restart can work without it, just with less context)
  const checkpoint = readSessionCheckpoint(root);

  // Validate run_id agreement if checkpoint exists
  if (checkpoint && checkpoint.run_id !== state.run_id) {
    console.log(chalk.red(`Checkpoint run_id mismatch: session.json has ${checkpoint.run_id}, state.json has ${state.run_id}`));
    console.log(chalk.dim('The checkpoint is stale. Proceeding with state.json as ground truth.'));
  }

  // Check terminal states
  if (state.status === 'completed') {
    console.log(chalk.red('Run is in terminal state: completed.'));
    console.log(chalk.dim(`Run ${state.run_id} completed at ${state.completed_at || 'unknown'}.`));
    process.exit(1);
  }

  if (state.status === 'failed') {
    console.log(chalk.red('Run uses reserved status: failed.'));
    console.log(chalk.dim('Current governed writers do not emit run-level failed. Inspect state.json and recover manually.'));
    process.exit(1);
  }

  if (state.status === 'blocked') {
    console.log(chalk.red('Run is blocked. Resolve the blocker first.'));
    const recovery = deriveRecoveryDescriptor(state, config);
    if (recovery) {
      console.log(chalk.dim(`Reason: ${recovery.typed_reason}`));
      console.log(chalk.dim(`Owner: ${recovery.owner}`));
      console.log(chalk.dim(`Action: ${recovery.recovery_action}`));
      if (recovery.detail) {
        console.log(chalk.dim(`Detail: ${recovery.detail}`));
      }
    } else if (state.blocked_reason) {
      console.log(chalk.dim(`Reason: ${typeof state.blocked_reason === 'string' ? state.blocked_reason : JSON.stringify(state.blocked_reason)}`));
    }
    process.exit(1);
  }

  // ── BUG-18: State/bundle integrity check ─────────────────────────────────
  const desync = detectStateBundleDesync(root, state);
  if (!desync.ok) {
    console.log(chalk.red('State/bundle integrity failure detected:'));
    for (const entry of desync.desynced) {
      console.log(chalk.red(`  Active turn ${entry.turn_id} (${entry.role}) has no dispatch bundle at ${entry.expected_path}`));
    }
    console.log('');
    console.log(chalk.dim('This is a ghost turn — state references an active turn but the dispatch files are missing.'));
    console.log(chalk.dim('Recovery options:'));
    for (const entry of desync.desynced) {
      console.log(`  ${chalk.cyan(`agentxchain reissue-turn --turn ${entry.turn_id} --reason "missing dispatch bundle"`)}`);
    }
    console.log(`  ${chalk.cyan('agentxchain reject-turn --reason "ghost turn — missing dispatch bundle"')}`);
    console.log('');
    console.log(chalk.dim('Run `agentxchain doctor` for a full diagnostic.'));
    process.exit(1);
  }

  // ── Repo-drift detection ────────────────────────────────────────────────
  const driftWarnings = [];
  if (checkpoint?.baseline_ref) {
    const currentBaseline = captureBaselineRef(root);
    const prev = checkpoint.baseline_ref;

    if (prev.git_head && currentBaseline.git_head && prev.git_head !== currentBaseline.git_head) {
      driftWarnings.push(`Git HEAD has moved since checkpoint: ${prev.git_head.slice(0, 8)} → ${currentBaseline.git_head.slice(0, 8)}`);
    }
    if (prev.git_branch && currentBaseline.git_branch && prev.git_branch !== currentBaseline.git_branch) {
      driftWarnings.push(`Branch changed since checkpoint: ${prev.git_branch} → ${currentBaseline.git_branch}`);
    }
    if (prev.workspace_dirty === false && currentBaseline.workspace_dirty === true) {
      driftWarnings.push('Workspace was clean at checkpoint but is now dirty');
    }
  }

  if (driftWarnings.length > 0) {
    for (const warning of driftWarnings) {
      console.log(chalk.yellow(`⚠ ${warning}`));
    }
  }

  const continuityAction = deriveRecommendedContinuityAction(state);

  // ── Pending gate / completion check ────────────────────────────────────
  if (state.pending_phase_transition) {
    const pt = state.pending_phase_transition;
    console.log(chalk.yellow(`Pending phase transition: ${pt.from} → ${pt.to} (gate: ${pt.gate})`));
    console.log(chalk.dim(`Run \`${continuityAction.recommended_command}\` next.`));
    if (continuityAction.recommended_detail) {
      console.log(chalk.dim(`Detail: ${continuityAction.recommended_detail}`));
    }
  }

  if (state.pending_run_completion) {
    const pc = state.pending_run_completion;
    console.log(chalk.yellow(`Pending run completion (gate: ${pc.gate})`));
    console.log(chalk.dim(`Run \`${continuityAction.recommended_command}\` next.`));
    if (continuityAction.recommended_detail) {
      console.log(chalk.dim(`Detail: ${continuityAction.recommended_detail}`));
    }
  }

  // Handle abandoned active turns (assigned but never completed)
  const activeTurns = getActiveTurns(state);
  const activeTurnCount = getActiveTurnCount(state);
  if (activeTurnCount > 0 && state.status === 'active') {
    const turnIds = Object.keys(activeTurns);
    console.log(chalk.yellow(`Warning: ${activeTurnCount} turn(s) were assigned but never completed: ${turnIds.join(', ')}`));
    console.log(chalk.dim('These turns will be available for the next agent to complete.'));

    // Fail closed if retained turn + irreconcilable drift — BUG-10 fix: surface actionable recovery
    if (driftWarnings.length > 0) {
      console.log(chalk.yellow('Active turns exist with repo drift since checkpoint. Reconnecting with warnings.'));
      console.log('');
      console.log(chalk.dim('Recovery options:'));
      for (const turnId of turnIds) {
        const turn = activeTurns[turnId];
        console.log(`  ${chalk.cyan(`agentxchain reissue-turn --turn ${turnId} --reason "baseline drift"`)}  — reissue ${turn.assigned_role} from current HEAD`);
      }
      console.log(`  ${chalk.cyan('agentxchain reject-turn --reason "baseline drift"')}  — reject and retry with refreshed baseline`);
      console.log(`  ${chalk.dim('Continue as-is if the drift does not affect the retained turns.')}`);
    }
  }

  // If pending gate/completion, do not bypass — surface and exit with recovery
  if (state.pending_phase_transition || state.pending_run_completion) {
    // Write checkpoint for the reconnect
    writeSessionCheckpoint(root, state, 'restart_reconnect');

    const recoveryReport = generateRecoveryReport(root, state, checkpoint, driftWarnings);
    const recoveryPath = join(root, '.agentxchain/SESSION_RECOVERY.md');
    const recoveryDir = dirname(recoveryPath);
    if (!existsSync(recoveryDir)) mkdirSync(recoveryDir, { recursive: true });
    writeFileSync(recoveryPath, recoveryReport);
    console.log(chalk.dim(`  Recovery report: .agentxchain/SESSION_RECOVERY.md`));
    return;
  }

  // If paused or idle without a pending approval gate, reactivate.
  if (state.status === 'paused' || state.status === 'idle') {
    const reactivated = reactivateGovernedRun(root, state, {
      reason: 'session_restart',
    });
    if (!reactivated.ok) {
      console.log(chalk.red(`Failed to reactivate run: ${reactivated.error}`));
      process.exit(1);
    }
    if (reactivated.migration_notice) {
      console.log(chalk.yellow(reactivated.migration_notice));
    }
    if (reactivated.phantom_notice) {
      console.log(chalk.yellow(reactivated.phantom_notice));
    }
  }

  // Determine role from option or routing
  const phase = state.phase || state.current_phase;
  const routing = config.routing?.[phase];
  const roleId = opts.role || routing?.entry_role || Object.keys(config.roles || {})[0] || null;

  if (!roleId) {
    console.log(chalk.red('Cannot determine which role to assign. Use --role to specify.'));
    process.exit(1);
  }

  // Assign next turn if no active turn exists
  if (activeTurnCount === 0) {
    // BUG-21 fix: consume approved intents (same as resume path) so intent_id
    // propagates into turn metadata and all lifecycle events.
    const consumed = consumeNextApprovedIntent(root, { role: roleId, run_id: state?.run_id || null });
    let assignedState;
    let turnId;
    let assignedRole = roleId;

    if (consumed.ok) {
      // Intake path handled the turn assignment with intakeContext
      assignedState = loadProjectState(root, config);
      if (!assignedState) {
        console.log(chalk.red('Failed to reload governed state after intake binding.'));
        process.exit(1);
      }
      turnId = consumed.turn_id;
      assignedRole = consumed.role || roleId;
      console.log(chalk.green(`Bound approved intent to next turn: ${consumed.intentId}`));
    } else {
      // No approved intents — plain assignment
      const assignment = assignGovernedTurn(root, config, roleId);
      if (!assignment.ok) {
        console.log(chalk.red(`Failed to assign turn: ${assignment.error}`));
        process.exit(1);
      }
      for (const warning of assignment.warnings || []) {
        console.log(chalk.yellow(`Warning: ${warning}`));
      }
      assignedState = assignment.state;
      turnId = assignment.turn?.turn_id || assignment.turn?.id;
      assignedRole = assignment.turn?.assigned_role || roleId;
    }

    // BUG-17 fix: write dispatch bundle AFTER state assignment succeeds.
    // The bundle must exist on disk before we report success, otherwise the
    // operator sees a "ghost turn" in state with no dispatch directory.
    if (turnId) {
      const bundleResult = writeDispatchBundle(root, assignedState, config, { turnId });
      if (!bundleResult.ok) {
        console.log(chalk.red(`Turn assigned but dispatch bundle write failed: ${bundleResult.error}`));
        console.log(chalk.dim('The turn is assigned in state but has no dispatch context.'));
        console.log(chalk.dim('Run `agentxchain reissue-turn` to reissue with a fresh bundle.'));
        process.exit(1);
      }
      for (const bw of bundleResult.warnings || []) {
        console.log(chalk.yellow(`Dispatch bundle warning: ${bw}`));
      }
    }

    // assignGovernedTurn already writes a checkpoint at turn_assigned

    console.log(chalk.green(`✓ Restarted run ${state.run_id}`));
    console.log(chalk.dim(`  Phase: ${phase}`));
    console.log(chalk.dim(`  Turn: ${turnId || 'assigned'}`));
    console.log(chalk.dim(`  Role: ${assignedRole || 'routing default'}`));
    console.log(chalk.dim(`  Dispatch: ${getDispatchTurnDir(turnId || 'unknown')}/`));
    if (checkpoint) {
      console.log(chalk.dim(`  Last checkpoint: ${checkpoint.checkpoint_reason} at ${checkpoint.last_checkpoint_at}`));
    }
  } else {
    // Reconnect to existing active turns — write checkpoint
    writeSessionCheckpoint(root, state, 'restart_reconnect');

    console.log(chalk.green(`✓ Reconnected to run ${state.run_id}`));
    console.log(chalk.dim(`  Phase: ${phase}`));
    console.log(chalk.dim(`  Active turns: ${Object.keys(activeTurns).join(', ')}`));
    console.log(chalk.dim('  Complete the active turn(s) with `agentxchain accept-turn` or `agentxchain step`.'));
  }

  // Write session recovery report
  const recoveryReport = generateRecoveryReport(root, state, checkpoint, driftWarnings);
  const recoveryPath = join(root, '.agentxchain/SESSION_RECOVERY.md');
  const recoveryDir = dirname(recoveryPath);
  if (!existsSync(recoveryDir)) mkdirSync(recoveryDir, { recursive: true });
  writeFileSync(recoveryPath, recoveryReport);
  console.log(chalk.dim(`  Recovery report: .agentxchain/SESSION_RECOVERY.md`));
}
