import { strict as assert } from 'node:assert';
import { describe, it } from 'node:test';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');

function read(relPath) {
  return readFileSync(join(REPO_ROOT, relPath), 'utf8');
}

function readJson(relPath) {
  return JSON.parse(read(relPath));
}

const PACKAGE = readJson('cli/package.json');
const CHANGELOG = read('cli/CHANGELOG.md');
const SIDEBARS = read('website-v2/sidebars.ts');
const HOME = read('website-v2/src/pages/index.tsx');
const PROTOCOL_DOCS = read('website-v2/docs/protocol.mdx');
const CAPABILITIES = readJson('.agentxchain-conformance/capabilities.json');
const IMPLEMENTOR_GUIDE = read('website-v2/docs/protocol-implementor-guide.mdx');
const LAUNCH_EVIDENCE = read('.planning/LAUNCH_EVIDENCE_REPORT.md');
const LLMS = read('website-v2/static/llms.txt');
// sitemap.xml is now auto-generated by Docusaurus at build time (no static file)
const HOMEBREW_FORMULA = read('cli/homebrew/agentxchain.rb');
const HOMEBREW_README = read('cli/homebrew/README.md');
const CURRENT_VERSION = process.env.AGENTXCHAIN_RELEASE_TARGET_VERSION || PACKAGE.version;
const CURRENT_RELEASE_DOC_ID = `releases/v${CURRENT_VERSION.replace(/\./g, '-')}`;
const CURRENT_RELEASE_DOC_PATH = `website-v2/docs/${CURRENT_RELEASE_DOC_ID}.mdx`;
const CURRENT_TARBALL_URL = `https://registry.npmjs.org/agentxchain/-/agentxchain-${CURRENT_VERSION}.tgz`;
const CURRENT_RELEASE_ROUTE = `/docs/${CURRENT_RELEASE_DOC_ID}`;

function extractAggregateEvidenceLine(text, label) {
  const matches = [...text.matchAll(/^-\s+.*\b(\d+)\s+tests\b.*\b0 failures\b.*$/gm)];
  assert.ok(matches.length > 0, `${label} must include a concrete test-count evidence line with 0 failures`);
  const aggregate = matches.reduce((best, match) => {
    const count = Number(match[1]);
    if (!best || count > best.count) {
      return { count, line: match[0] };
    }
    return best;
  }, null);
  return aggregate.line
    .replace(/\*\*/g, '')
    .replace(/`/g, '')
    .trim();
}

function extractAggregateEvidenceCount(text, label) {
  const line = extractAggregateEvidenceLine(text, label);
  const match = line.match(/\b(\d+)\s+tests\b/);
  assert.ok(match, `${label} must contain a concrete test count`);
  return Number(match[1]);
}

function formatCount(value) {
  return new Intl.NumberFormat('en-US').format(value);
}

function extractReleaseSummaryParagraph(text, version) {
  const withoutFrontmatter = text.replace(/^---\n[\s\S]*?\n---\n*/, '').trim();
  const heading = `# AgentXchain v${version}`;
  const headingIndex = withoutFrontmatter.indexOf(heading);
  assert.notEqual(
    headingIndex,
    -1,
    `release notes page must contain the governed heading ${heading}`,
  );
  const afterHeading = withoutFrontmatter.slice(headingIndex + heading.length).trimStart();
  const match = afterHeading.match(/^([^\n#][\s\S]*?)\n\s*\n/);
  assert.ok(match, 'release notes page must contain a summary paragraph immediately after the governed heading');
  return match[1].replace(/\s+/g, ' ').trim();
}

function extractCurrentProtocolLabel(text) {
  const titleMatch = text.match(/^title:\s*(Protocol v\d+)$/m);
  assert.ok(titleMatch, 'protocol docs must declare a current title in frontmatter');
  return titleMatch[1];
}

describe('current release surface', () => {
  it('AT-CRS-001: changelog top heading matches current package version', () => {
    const topHeading = CHANGELOG.match(/^##\s+([0-9]+\.[0-9]+\.[0-9]+)$/m);
    assert.ok(topHeading, 'CHANGELOG.md must contain a version heading');
    assert.equal(topHeading[1], CURRENT_VERSION);
  });

  it('AT-CRS-002: current release notes page exists', () => {
    assert.ok(
      existsSync(join(REPO_ROOT, CURRENT_RELEASE_DOC_PATH)),
      `current release notes page must exist at ${CURRENT_RELEASE_DOC_PATH}`,
    );
  });

  it('AT-CRS-003: docs sidebar nests release notes under one collapsed Release Notes category', () => {
    assert.match(
      SIDEBARS,
      /label:\s*'Release Notes'[\s\S]*collapsible:\s*true[\s\S]*collapsed:\s*true[\s\S]*items:\s*\[[\s\S]*dirName:\s*'releases'/,
    );
    assert.ok(
      existsSync(join(REPO_ROOT, 'website-v2', 'docs', CURRENT_RELEASE_DOC_ID + '.mdx')),
      `release doc ${CURRENT_RELEASE_DOC_ID}.mdx must exist for auto-inclusion`,
    );
  });

  it('AT-CRS-004: homepage hero badge shows current package version', () => {
    assert.match(HOME, new RegExp(`v${CURRENT_VERSION.replace(/\./g, '\\.')}`));
  });

  it('AT-CRS-005: homepage proof stat shows the exact current aggregate test count', () => {
    const versionBlock = CHANGELOG.split(/^## \d+\.\d+\.\d+$/m).slice(0, 2).join('');
    const aggregateTestCount = extractAggregateEvidenceCount(versionBlock, 'changelog evidence');
    assert.match(
      HOME,
      new RegExp(`stat-number\">${formatCount(aggregateTestCount).replace(/,/g, ',')}`),
      'homepage proof stat must show the exact aggregate current-release test count',
    );
    assert.match(HOME, /stat-label">Tests \/ 0 failures</);
  });

  it('AT-CRS-006: homepage protocol-layer CTA matches the current protocol docs title', () => {
    const currentProtocolLabel = extractCurrentProtocolLabel(PROTOCOL_DOCS);
    assert.match(
      HOME,
      new RegExp(`linkText: '${currentProtocolLabel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}'`),
      'homepage protocol-layer CTA must use the current protocol docs title',
    );
  });

  it('AT-CRS-007: homepage connectors layer names all five shipped adapters', () => {
    const requiredAdapters = ['manual', 'local_cli', 'api_proxy', 'mcp', 'remote_agent'];
    for (const adapter of requiredAdapters) {
      assert.match(
        HOME,
        new RegExp(`\\b${adapter}\\b`),
        `homepage connectors layer must mention ${adapter}`,
      );
    }
    assert.doesNotMatch(HOME, /Three modes:/);
  });

  it('AT-CRS-008: conformance capabilities version matches current package version', () => {
    assert.equal(CAPABILITIES.version, CURRENT_VERSION);
  });

  it('AT-CRS-009: protocol implementor guide example shows current package version', () => {
    assert.match(IMPLEMENTOR_GUIDE, new RegExp(`"version": "${CURRENT_VERSION.replace(/\./g, '\\.')}"`));
  });

  it('AT-CRS-010: release notes page evidence section has concrete test counts', () => {
    const releasePage = read(CURRENT_RELEASE_DOC_PATH);
    const summary = extractReleaseSummaryParagraph(releasePage, CURRENT_VERSION);
    assert.ok(summary.length > 0, 'release notes summary paragraph must not be empty');
  });

  it('AT-CRS-011: release notes page evidence section has concrete test counts', () => {
    const releasePage = read(CURRENT_RELEASE_DOC_PATH);
    assert.match(releasePage, /## Evidence/i, 'release notes page must have an Evidence section');
    extractAggregateEvidenceLine(releasePage, 'release notes evidence');
  });

  it('AT-CRS-012: changelog and release notes evidence lines stay aligned', () => {
    const versionBlock = CHANGELOG.split(/^## \d+\.\d+\.\d+$/m).slice(0, 2).join('');
    const releasePage = read(CURRENT_RELEASE_DOC_PATH);
    const changelogEvidence = extractAggregateEvidenceLine(versionBlock, 'changelog evidence');
    const releaseEvidence = extractAggregateEvidenceLine(releasePage, 'release notes evidence');
    assert.equal(
      changelogEvidence,
      releaseEvidence,
      'top changelog aggregate evidence and current release-note aggregate evidence must match exactly',
    );
  });

  it('AT-CRS-013: launch evidence title carries the current release version', () => {
    assert.match(
      LAUNCH_EVIDENCE,
      new RegExp(`^# Launch Evidence Report — AgentXchain v${CURRENT_VERSION.replace(/\./g, '\\.')}`, 'm'),
      'Launch evidence report title must track the current release version',
    );
  });

  it('AT-CRS-014: Homebrew mirror formula points at the current npm tarball', () => {
    assert.match(
      HOMEBREW_FORMULA,
      new RegExp(`url "${CURRENT_TARBALL_URL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`),
      'Homebrew mirror formula must track the current npm tarball URL',
    );
  });

  it('AT-CRS-015: Homebrew mirror maintainer README tracks the current version and tarball', () => {
    assert.match(
      HOMEBREW_README,
      new RegExp(`- version: \`${CURRENT_VERSION.replace(/\./g, '\\.')}\``),
      'Homebrew mirror README must track the current version',
    );
    assert.match(
      HOMEBREW_README,
      new RegExp(`- source tarball: \`${CURRENT_TARBALL_URL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\``),
      'Homebrew mirror README must track the current tarball URL',
    );
  });

  it('AT-CRS-016: llms.txt lists the current release-notes route', () => {
    assert.match(
      LLMS,
      new RegExp(CURRENT_RELEASE_ROUTE.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')),
      'llms.txt must list the current release-notes route',
    );
  });

  it('AT-CRS-017: sitemap is auto-generated by Docusaurus and includes all built docs', () => {
    // sitemap.xml is now auto-generated at build time — every doc that builds is included.
    // This test verifies the release doc file exists (which guarantees sitemap inclusion).
    const releaseDocPath = join(REPO_ROOT, 'website-v2', 'docs', CURRENT_RELEASE_DOC_ID + '.mdx');
    assert.ok(
      existsSync(releaseDocPath),
      `release doc ${CURRENT_RELEASE_DOC_ID}.mdx must exist (auto-included in sitemap at build)`,
    );
  });
});
