import { strict as assert } from 'node:assert';
import { describe, it } from 'node:test';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  extractAggregateEvidenceLine as _extractAggregateEvidenceLine,
  formatCount,
  escapeRegExp,
} from '../src/lib/release-alignment.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');

function read(relPath) {
  return readFileSync(join(REPO_ROOT, relPath), 'utf8');
}

function readJson(relPath) {
  return JSON.parse(read(relPath));
}

const PACKAGE = readJson('cli/package.json');
const CHANGELOG = read('cli/CHANGELOG.md');
const SIDEBARS = read('website-v2/sidebars.ts');
const ROOT_README = read('README.md');
const CLI_README = read('cli/README.md');
const HOME = read('website-v2/src/pages/index.tsx');
const WHY_PAGE = read('website-v2/src/pages/why.mdx');
const PROTOCOL_DOCS = read('website-v2/docs/protocol.mdx');
const CAPABILITIES = readJson('.agentxchain-conformance/capabilities.json');
const IMPLEMENTOR_GUIDE = read('website-v2/docs/protocol-implementor-guide.mdx');
const LAUNCH_EVIDENCE = read('.planning/LAUNCH_EVIDENCE_REPORT.md');
const LLMS = read('website-v2/static/llms.txt');
// sitemap.xml is now auto-generated by Docusaurus at build time (no static file)
const HOMEBREW_FORMULA = read('cli/homebrew/agentxchain.rb');
const HOMEBREW_README = read('cli/homebrew/README.md');
const CURRENT_VERSION = process.env.AGENTXCHAIN_RELEASE_TARGET_VERSION || PACKAGE.version;
const CURRENT_RELEASE_DOC_ID = `releases/v${CURRENT_VERSION.replace(/\./g, '-')}`;
const CURRENT_RELEASE_DOC_PATH = `website-v2/docs/${CURRENT_RELEASE_DOC_ID}.mdx`;
const CURRENT_TARBALL_URL = `https://registry.npmjs.org/agentxchain/-/agentxchain-${CURRENT_VERSION}.tgz`;
const CURRENT_RELEASE_ROUTE = `/docs/${CURRENT_RELEASE_DOC_ID}`;
const BUG52_BUG53_SHIP_DOC_PATH = 'website-v2/docs/releases/v2-147-0.mdx';

function extractAggregateEvidenceLine(text, label) {
  const line = _extractAggregateEvidenceLine(text);
  assert.ok(line, `${label} must include a concrete test-count evidence line with 0 failures`);
  return line;
}

function extractAggregateEvidenceCount(text, label) {
  const line = extractAggregateEvidenceLine(text, label);
  const match = line.match(/\b(\d[\d,]*)\s+tests\b/);
  assert.ok(match, `${label} must contain a concrete test count`);
  return Number(match[1].replace(/,/g, ''));
}

function extractReleaseSummaryParagraph(text, version) {
  const withoutFrontmatter = text.replace(/^---\n[\s\S]*?\n---\n*/, '').trim();
  const heading = `# AgentXchain v${version}`;
  const headingIndex = withoutFrontmatter.indexOf(heading);
  assert.notEqual(
    headingIndex,
    -1,
    `release notes page must contain the governed heading ${heading}`,
  );
  const afterHeading = withoutFrontmatter.slice(headingIndex + heading.length).trimStart();
  const match = afterHeading.match(/^([^\n#][\s\S]*?)\n\s*\n/);
  assert.ok(match, 'release notes page must contain a summary paragraph immediately after the governed heading');
  return match[1].replace(/\s+/g, ' ').trim();
}

function extractCurrentProtocolLabel(text) {
  const titleMatch = text.match(/^title:\s*(Protocol v\d+)$/m);
  assert.ok(titleMatch, 'protocol docs must declare a current title in frontmatter');
  return titleMatch[1];
}

function assertNamesAllAdapters(text, label) {
  const requiredAdapters = ['manual', 'local_cli', 'api_proxy', 'mcp', 'remote_agent'];
  for (const adapter of requiredAdapters) {
    assert.match(
      text,
      new RegExp(`\\b${adapter}\\b`),
      `${label} must mention ${adapter}`,
    );
  }
}

describe('current release surface', () => {
  it('AT-CRS-001: changelog top heading matches current package version', () => {
    const topHeading = CHANGELOG.match(/^##\s+([0-9]+\.[0-9]+\.[0-9]+)$/m);
    assert.ok(topHeading, 'CHANGELOG.md must contain a version heading');
    assert.equal(topHeading[1], CURRENT_VERSION);
  });

  it('AT-CRS-002: current release notes page exists', () => {
    assert.ok(
      existsSync(join(REPO_ROOT, CURRENT_RELEASE_DOC_PATH)),
      `current release notes page must exist at ${CURRENT_RELEASE_DOC_PATH}`,
    );
  });

  it('AT-CRS-003: docs sidebar nests release notes under one collapsed Release Notes category', () => {
    assert.match(
      SIDEBARS,
      /label:\s*'Release Notes'[\s\S]*collapsible:\s*true[\s\S]*collapsed:\s*true[\s\S]*items:\s*\[[\s\S]*dirName:\s*'releases'/,
    );
    assert.ok(
      existsSync(join(REPO_ROOT, 'website-v2', 'docs', CURRENT_RELEASE_DOC_ID + '.mdx')),
      `release doc ${CURRENT_RELEASE_DOC_ID}.mdx must exist for auto-inclusion`,
    );
  });

  it('AT-CRS-004: homepage hero badge shows current package version', () => {
    assert.match(HOME, new RegExp(`v${CURRENT_VERSION.replace(/\./g, '\\.')}`));
  });

  it('AT-CRS-005: homepage proof stat shows the exact current aggregate test count', () => {
    const versionBlock = CHANGELOG.split(/^## \d+\.\d+\.\d+$/m).slice(0, 2).join('');
    const aggregateTestCount = extractAggregateEvidenceCount(versionBlock, 'changelog evidence');
    assert.match(
      HOME,
      new RegExp(`stat-number\">${formatCount(aggregateTestCount).replace(/,/g, ',')}`),
      'homepage proof stat must show the exact aggregate current-release test count',
    );
    assert.match(HOME, /stat-label">Tests \/ 0 failures</);
  });

  it('AT-CRS-006: homepage protocol-layer CTA matches the current protocol docs title', () => {
    const currentProtocolLabel = extractCurrentProtocolLabel(PROTOCOL_DOCS);
    assert.match(
      HOME,
      new RegExp(`linkText: '${currentProtocolLabel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}'`),
      'homepage protocol-layer CTA must use the current protocol docs title',
    );
  });

  it('AT-CRS-007: homepage connectors layer names all five shipped adapters', () => {
    const requiredAdapters = ['manual', 'local_cli', 'api_proxy', 'mcp', 'remote_agent'];
    for (const adapter of requiredAdapters) {
      assert.match(
        HOME,
        new RegExp(`\\b${adapter}\\b`),
        `homepage connectors layer must mention ${adapter}`,
      );
    }
    assert.doesNotMatch(HOME, /Three modes:/);
  });

  it('AT-CRS-008: conformance capabilities version matches current package version', () => {
    assert.equal(CAPABILITIES.version, CURRENT_VERSION);
  });

  it('AT-CRS-009: protocol implementor guide example shows current package version', () => {
    assert.match(IMPLEMENTOR_GUIDE, new RegExp(`"version": "${CURRENT_VERSION.replace(/\./g, '\\.')}"`));
  });

  it('AT-CRS-010: release notes page evidence section has concrete test counts', () => {
    const releasePage = read(CURRENT_RELEASE_DOC_PATH);
    const summary = extractReleaseSummaryParagraph(releasePage, CURRENT_VERSION);
    assert.ok(summary.length > 0, 'release notes summary paragraph must not be empty');
  });

  it('AT-CRS-011: release notes page evidence section has concrete test counts', () => {
    const releasePage = read(CURRENT_RELEASE_DOC_PATH);
    assert.match(releasePage, /## Evidence/i, 'release notes page must have an Evidence section');
    extractAggregateEvidenceLine(releasePage, 'release notes evidence');
  });

  it('AT-CRS-012: changelog and release notes evidence lines stay aligned', () => {
    const versionBlock = CHANGELOG.split(/^## \d+\.\d+\.\d+$/m).slice(0, 2).join('');
    const releasePage = read(CURRENT_RELEASE_DOC_PATH);
    const changelogEvidence = extractAggregateEvidenceLine(versionBlock, 'changelog evidence');
    const releaseEvidence = extractAggregateEvidenceLine(releasePage, 'release notes evidence');
    assert.equal(
      changelogEvidence,
      releaseEvidence,
      'top changelog aggregate evidence and current release-note aggregate evidence must match exactly',
    );
  });

  it('AT-CRS-013: launch evidence title carries the current release version', () => {
    assert.match(
      LAUNCH_EVIDENCE,
      new RegExp(`^# Launch Evidence Report — AgentXchain v${CURRENT_VERSION.replace(/\./g, '\\.')}`, 'm'),
      'Launch evidence report title must track the current release version',
    );
  });

  it('AT-CRS-014: Homebrew mirror formula points at the current npm tarball', () => {
    assert.match(
      HOMEBREW_FORMULA,
      new RegExp(`url "${CURRENT_TARBALL_URL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`),
      'Homebrew mirror formula must track the current npm tarball URL',
    );
  });

  it('AT-CRS-015: Homebrew mirror maintainer README tracks the current version and tarball', () => {
    assert.match(
      HOMEBREW_README,
      new RegExp(`- version: \`${CURRENT_VERSION.replace(/\./g, '\\.')}\``),
      'Homebrew mirror README must track the current version',
    );
    assert.match(
      HOMEBREW_README,
      new RegExp(`- source tarball: \`${CURRENT_TARBALL_URL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\``),
      'Homebrew mirror README must track the current tarball URL',
    );
  });

  it('AT-CRS-016: llms.txt lists the current release-notes route', () => {
    assert.match(
      LLMS,
      new RegExp(CURRENT_RELEASE_ROUTE.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')),
      'llms.txt must list the current release-notes route',
    );
  });

  it('AT-CRS-017: sitemap is auto-generated by Docusaurus and includes all built docs', () => {
    // sitemap.xml is now auto-generated at build time — every doc that builds is included.
    // This test verifies the release doc file exists (which guarantees sitemap inclusion).
    const releaseDocPath = join(REPO_ROOT, 'website-v2', 'docs', CURRENT_RELEASE_DOC_ID + '.mdx');
    assert.ok(
      existsSync(releaseDocPath),
      `release doc ${CURRENT_RELEASE_DOC_ID}.mdx must exist (auto-included in sitemap at build)`,
    );
  });

  it('AT-CRS-018: root README uses the current protocol label and names all five shipped adapters', () => {
    const currentProtocolLabel = extractCurrentProtocolLabel(PROTOCOL_DOCS);
    assert.match(
      ROOT_README,
      new RegExp(`\\[${currentProtocolLabel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\]\\(https://agentxchain\\.dev/docs/protocol/?\\)`),
      'root README must link to protocol docs with the current title',
    );
    assertNamesAllAdapters(ROOT_README, 'root README');
    assert.doesNotMatch(ROOT_README, /Protocol spec \(v6\)/);
  });

  it('AT-CRS-019: cli README uses the current protocol label and names all five shipped adapters', () => {
    const currentProtocolLabel = extractCurrentProtocolLabel(PROTOCOL_DOCS);
    assert.match(
      CLI_README,
      new RegExp(`\\[${currentProtocolLabel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\]\\(https://agentxchain\\.dev/docs/protocol/?\\)`),
      'cli README must link to protocol docs with the current title',
    );
    assertNamesAllAdapters(CLI_README, 'cli README');
    assert.doesNotMatch(CLI_README, /Protocol spec \(v6\)/);
  });

  it('AT-CRS-020: why page names all five shipped adapters and rejects stale three-adapter framing', () => {
    assertNamesAllAdapters(WHY_PAGE, 'why page');
    assert.doesNotMatch(WHY_PAGE, /Three adapter modes/i);
  });

  it('AT-CRS-021: homepage platform split names all five shipped adapters and rejects stale four-adapter copy', () => {
    assert.match(
      HOME,
      /All connectors:\s*manual,\s*local_cli,\s*api_proxy,\s*mcp,\s*remote_agent/i,
      'homepage platform split must list all five shipped adapters',
    );
    assert.doesNotMatch(HOME, /All connectors:\s*manual,\s*local_cli,\s*api_proxy,\s*MCP\b/);
  });

  it('AT-CRS-022: current release notes include the tester rerun contract for shipped-package closure proof', () => {
    const releasePage = read(CURRENT_RELEASE_DOC_PATH);
    assert.match(
      releasePage,
      /## Tester Re-Run Contract/i,
      'current release notes must include a dedicated tester rerun contract section for shipped-package verification',
    );
    assert.match(
      releasePage,
      new RegExp(`agentxchain@${escapeRegExp(CURRENT_VERSION)}`),
      'tester rerun contract must name the exact shipped package version',
    );
    for (const term of [
      'startup_latency_ms',
      'elapsed_since_spawn_ms',
      'runtimes.<id>.startup_watchdog_ms',
      'undeclared_verification_outputs',
      'verification.produced_files',
      'git status --short',
      'accept-turn` followed by `checkpoint-turn',
      'Clean tree means BUG-55 is fixed for your reproduction',
      'phase_entered',
      'reconciled_before_dispatch',
      'session_continuation',
    ]) {
      assert.match(
        releasePage,
        new RegExp(escapeRegExp(term)),
        `tester rerun contract must mention ${term}`,
      );
    }
  });

  it('AT-CRS-023: v2.147.0 release notes redirect still-open closure work to the latest shipped rerun contract', () => {
    const priorReleasePage = read(BUG52_BUG53_SHIP_DOC_PATH);
    assert.match(
      priorReleasePage,
      /For tester closure evidence on still-open bugs/i,
      'v2.147.0 release notes must redirect operators to the latest shipped rerun contract',
    );
    assert.match(
      priorReleasePage,
      new RegExp(escapeRegExp(`${CURRENT_RELEASE_ROUTE}#tester-re-run-contract`)),
      'v2.147.0 release notes must link to the latest shipped tester rerun contract anchor',
    );
  });
});
