import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'fs';
import { resolve } from 'path';

const DOCS_ROOT = resolve(import.meta.dirname, '../../website-v2/docs');

function readDoc(name) {
  return readFileSync(resolve(DOCS_ROOT, name), 'utf8');
}

describe('Timeout docs content guard', () => {
  const content = readDoc('timeouts.mdx');

  it('documents the timeouts config shape and scopes', () => {
    assert.ok(content.includes('timeouts'), 'must document timeouts config key');
    assert.ok(content.includes('per_turn_minutes'), 'must document per_turn_minutes');
    assert.ok(content.includes('per_phase_minutes'), 'must document per_phase_minutes');
    assert.ok(content.includes('per_run_minutes'), 'must document per_run_minutes');
    assert.ok(content.includes('turn, phase, and run'), 'must document all timeout scopes');
  });

  it('documents action semantics and skip_phase constraint', () => {
    assert.ok(content.includes('escalate'), 'must document escalate action');
    assert.ok(content.includes('warn'), 'must document warn action');
    assert.ok(content.includes('skip_phase'), 'must document skip_phase action');
    assert.ok(content.includes('routing-only'), 'must document skip_phase as routing-only');
  });

  it('documents the actual enforcement boundary and rejects ghost approval-boundary claims', () => {
    assert.match(content, /agentxchain run|runLoop/i,
      'must document run/runLoop as the in-flight dispatch timeout enforcement surface');
    assert.match(content, /accept-turn/i, 'must document accept-turn as the mutating timeout boundary');
    assert.match(content, /status/i, 'must document status as the read-only timeout surface');
    assert.match(content, /do not currently re-run timeout mutation/i,
      'must explicitly state that approval commands do not currently re-run timeout mutation');
  });

  it('documents the approval-pending exemption (DEC-APPROVAL-TIMEOUT-EXEMPT-001)', () => {
    assert.match(content, /approval-pending exemption/i,
      'must have an approval-pending exemption section');
    assert.match(content, /pending_phase_transition|pending_run_completion/i,
      'must name the specific pending states that are exempt');
    assert.match(content, /evaluateTimeouts.*accept-turn|accept-turn.*evaluateTimeouts/i,
      'must document that evaluateTimeouts is only called from accept-turn');
    assert.match(content, /do\s*\*\*not\*\*\s*pause the wall clock|do not pause the wall clock|clock.*continue/i,
      'must document that approval waits do not pause the wall clock');
    assert.match(content, /next accepted turn can immediately block|immediately block on `timeout:phase` or `timeout:run`/i,
      'must document the next-acceptance timeout trap explicitly');
  });

  it('documents operator surfaces and recovery', () => {
    assert.ok(content.includes('agentxchain status'), 'must document status visibility');
    assert.ok(content.includes('agentxchain report'), 'must document report visibility');
    assert.ok(content.includes('agentxchain resume'), 'must document recovery command');
    assert.ok(content.includes('/docs/recovery'), 'must link to recovery docs');
  });

  it('documents remaining timeout budget visibility in status and turn show', () => {
    assert.ok(content.includes('remaining'), 'must document remaining budget display');
    assert.ok(content.includes('deadline'), 'must document deadline display');
    assert.ok(content.includes('turn show'), 'must document turn show budget visibility');
    assert.ok(content.includes('timeout_budget'), 'must document timeout_budget in JSON output');
  });

  it('is linked from docs navigation and discovery surfaces', () => {
    const sidebars = readFileSync(resolve(DOCS_ROOT, '../sidebars.ts'), 'utf8');
    const llms = readFileSync(resolve(DOCS_ROOT, '../static/llms.txt'), 'utf8');
    assert.ok(sidebars.includes("'timeouts'"), 'timeouts must be in sidebars.ts');
    assert.ok(llms.includes('/docs/timeouts'), 'timeouts must be in llms.txt');
    // sitemap.xml is auto-generated by Docusaurus — all built docs are included automatically
  });
});
