import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..', '..');
const CLI = resolve(ROOT, 'cli');
const SCRIPT = resolve(CLI, 'scripts', 'render-github-release-body.mjs');
const PACKAGE = JSON.parse(readFileSync(resolve(CLI, 'package.json'), 'utf8'));
const CURRENT_VERSION = PACKAGE.version;
const CURRENT_RELEASE_DOC = readFileSync(
  resolve(ROOT, 'website-v2', 'docs', 'releases', `v${CURRENT_VERSION.replace(/\./g, '-')}.mdx`),
  'utf8',
);

function extractSummaryParagraph(text, version) {
  const withoutFrontmatter = text.replace(/^---\n[\s\S]*?\n---\n*/, '').trim();
  const heading = `# AgentXchain v${version}`;
  assert.notEqual(
    withoutFrontmatter.indexOf(heading),
    -1,
    `release page must contain the governed heading ${heading}`,
  );
  const afterHeading = withoutFrontmatter.slice(withoutFrontmatter.indexOf(heading) + heading.length).trimStart();
  const match = afterHeading.match(/^([^\n#][\s\S]*?)\n\s*\n/);
  assert.ok(match, 'release page must contain a summary paragraph immediately after the governed heading');
  return match[1].replace(/\s+/g, ' ').trim();
}

describe('GitHub release body renderer', () => {
  it('AT-GRB-001: fails without --target-version', () => {
    const result = spawnSync('node', [SCRIPT], { cwd: CLI, encoding: 'utf8' });
    assert.notEqual(result.status, 0, 'renderer must fail without a target version');
    assert.match(result.stderr, /Usage:/, 'renderer must print usage on missing target version');
  });

  it('AT-GRB-002 AT-GRB-003 AT-GRB-004 AT-GRB-005: output points at governed release truth', () => {
    const output = execFileSync(
      'node',
      [SCRIPT, '--target-version', CURRENT_VERSION, '--repo', 'shivamtiwari93/agentXchain.dev'],
      { cwd: CLI, encoding: 'utf8' },
    );

    assert.match(
      output,
      new RegExp(`Public release notes: https://agentxchain\\.dev/docs/releases/v${CURRENT_VERSION.replace(/\./g, '-')}`),
    );
    assert.match(
      output,
      new RegExp(`npm package: https://www\\.npmjs\\.com/package/agentxchain/v/${CURRENT_VERSION.replace(/\./g, '\\.')}`),
    );

    const summary = extractSummaryParagraph(CURRENT_RELEASE_DOC, CURRENT_VERSION);
    assert.match(output, new RegExp(summary.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
    assert.match(output, /## Evidence/, 'output must include an Evidence section');
    assert.match(
      output,
      /-\s+\d+\s+tests\s+\/\s+\d+\s+suites\s+\/\s+0 failures/,
      'output must include a concrete aggregate evidence line',
    );
  });

  it('AT-GRB-006: publish workflow uses renderer output and repairs existing releases on rerun', () => {
    const workflow = readFileSync(resolve(ROOT, '.github', 'workflows', 'publish-npm-on-tag.yml'), 'utf8');
    assert.match(
      workflow,
      /render-github-release-body\.mjs/,
      'publish workflow must render a governed GitHub Release body',
    );
    assert.match(
      workflow,
      /gh release edit "\$TAG"[\s\S]*--notes-file "\$NOTES_FILE"/,
      'workflow must update an existing release body on rerun',
    );
    assert.match(
      workflow,
      /gh release create "\$TAG"[\s\S]*--notes-file "\$NOTES_FILE"/,
      'workflow must use the rendered notes file when creating a release',
    );
    assert.doesNotMatch(
      workflow,
      /gh release create "\$TAG"[\s\S]*--generate-notes/,
      'workflow must not fall back to autogenerated release notes as the primary release body',
    );
  });
});
