import { strict as assert } from 'node:assert';
import { describe, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');

function read(relPath) {
  return readFileSync(join(REPO_ROOT, relPath), 'utf8');
}

const SIDEBARS = read('website-v2/sidebars.ts');
const SPEC = read('.planning/DOCS_RELEASE_NOTES_SIDEBAR_SPEC.md');
const RELEASE_DOCS = readdirSync(join(REPO_ROOT, 'website-v2', 'docs', 'releases')).filter((entry) =>
  entry.endsWith('.mdx'),
);

function parseReleaseMeta(file) {
  const match = /^v(\d+)-(\d+)-(\d+)\.mdx$/.exec(file);
  assert.ok(match, `release note filename must be semver-shaped: ${file}`);
  const content = read(`website-v2/docs/releases/${file}`);
  const positionMatch = content.match(/^sidebar_position:\s*(-?\d+)\s*$/m);
  assert.ok(positionMatch, `${file} must declare sidebar_position`);
  return {
    file,
    version: match.slice(1).map(Number),
    sidebarPosition: Number(positionMatch[1]),
  };
}

function compareDesc(left, right) {
  for (let i = 0; i < 3; i += 1) {
    if (left.version[i] !== right.version[i]) {
      return right.version[i] - left.version[i];
    }
  }
  return 0;
}

describe('release notes sidebar contract', () => {
  it('AT-RNS-001: records the release notes sidebar contract in planning', () => {
    assert.match(SPEC, /^# Release Notes Sidebar Spec$/m);
  });

  it('AT-RNS-002: defines a single top-level Release Notes category', () => {
    const matches = [...SIDEBARS.matchAll(/label:\s*'Release Notes'/g)];
    assert.equal(matches.length, 1, 'sidebar must define exactly one Release Notes category');
  });

  it('AT-RNS-003: keeps the Release Notes category collapsible and collapsed by default', () => {
    assert.match(
      SIDEBARS,
      /label:\s*'Release Notes'[\s\S]*collapsible:\s*true[\s\S]*collapsed:\s*true/,
    );
  });

  it('AT-RNS-004: auto-generates every release note under the Release Notes category', () => {
    assert.ok(RELEASE_DOCS.length > 0, 'release notes directory must contain release pages');
    assert.match(
      SIDEBARS,
      /label:\s*'Release Notes'[\s\S]*items:\s*\[[\s\S]*type:\s*'autogenerated'[\s\S]*dirName:\s*'releases'/,
    );
  });

  it('AT-RNS-005: release-note sidebar positions are unique', () => {
    const positions = RELEASE_DOCS.map((file) => parseReleaseMeta(file).sidebarPosition);
    assert.equal(
      new Set(positions).size,
      positions.length,
      'release-note sidebar_position values must be unique',
    );
  });

  it('AT-RNS-006: release-note sidebar order matches reverse semver order', () => {
    const actual = RELEASE_DOCS
      .map(parseReleaseMeta)
      .sort((left, right) => left.sidebarPosition - right.sidebarPosition)
      .map((entry) => entry.file);

    const expected = RELEASE_DOCS
      .map(parseReleaseMeta)
      .sort(compareDesc)
      .map((entry) => entry.file);

    assert.deepEqual(
      actual,
      expected,
      'sorting by sidebar_position must yield newest release first',
    );
  });

  it('AT-RNS-007: no release doc has duplicate front matter keys', () => {
    for (const file of RELEASE_DOCS) {
      const content = read(`website-v2/docs/releases/${file}`);
      const fmEnd = content.indexOf('\n---\n', 4);
      assert.ok(fmEnd > 0, `${file} must have closing frontmatter delimiter`);
      const frontmatter = content.slice(4, fmEnd);
      const keys = frontmatter.split('\n')
        .map((line) => line.match(/^(\w[\w_]*):\s/))
        .filter(Boolean)
        .map((m) => m[1]);
      const seen = new Set();
      for (const key of keys) {
        assert.ok(!seen.has(key), `${file} has duplicate front matter key: ${key}`);
        seen.add(key);
      }
    }
  });
});
