import { strict as assert } from 'node:assert';
import { describe, it } from 'node:test';
import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');

function read(relPath) {
  return readFileSync(join(REPO_ROOT, relPath), 'utf8');
}

const SIDEBARS = read('website-v2/sidebars.ts');
const SPEC = read('.planning/DOCS_RELEASE_NOTES_SIDEBAR_SPEC.md');
const RELEASE_DOCS = readdirSync(join(REPO_ROOT, 'website-v2', 'docs', 'releases')).filter((entry) =>
  entry.endsWith('.mdx'),
);

describe('release notes sidebar contract', () => {
  it('AT-RNS-001: records the release notes sidebar contract in planning', () => {
    assert.match(SPEC, /^# Release Notes Sidebar Spec$/m);
  });

  it('AT-RNS-002: defines a single top-level Release Notes category', () => {
    const matches = [...SIDEBARS.matchAll(/label:\s*'Release Notes'/g)];
    assert.equal(matches.length, 1, 'sidebar must define exactly one Release Notes category');
  });

  it('AT-RNS-003: keeps the Release Notes category collapsible and collapsed by default', () => {
    assert.match(
      SIDEBARS,
      /label:\s*'Release Notes'[\s\S]*collapsible:\s*true[\s\S]*collapsed:\s*true/,
    );
  });

  it('AT-RNS-004: auto-generates every release note under the Release Notes category', () => {
    assert.ok(RELEASE_DOCS.length > 0, 'release notes directory must contain release pages');
    assert.match(
      SIDEBARS,
      /label:\s*'Release Notes'[\s\S]*items:\s*\[[\s\S]*type:\s*'autogenerated'[\s\S]*dirName:\s*'releases'/,
    );
  });
});
