import { after, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { chmodSync, cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import {
  RELEASE_ALIGNMENT_SCOPES,
  RELEASE_ALIGNMENT_SURFACES,
  validateReleaseAlignment,
} from '../src/lib/release-alignment.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');
const CHECK_SCRIPT = join(REPO_ROOT, 'cli', 'scripts', 'check-release-alignment.mjs');
const ALIGNMENT_LIB = join(REPO_ROOT, 'cli', 'src', 'lib', 'release-alignment.js');
const PLAYBOOK = join(REPO_ROOT, '.planning', 'RELEASE_PLAYBOOK.md');
const SPEC = join(REPO_ROOT, '.planning', 'RELEASE_ALIGNMENT_MANIFEST_SPEC.md');
const FIXTURES = [];

function writeOnboardingDocs(root, version) {
  const prereqBlock = [
    '# Doc',
    '',
    '## Prerequisites',
    '',
    `- Minimum CLI version: \`agentxchain ${version}\` or newer`,
    '- Check your installed binary: `agentxchain --version`',
    '- Upgrade with npm: `npm install -g agentxchain@latest`',
    '- Upgrade with Homebrew: `brew upgrade agentxchain`',
    '- If the binary on `PATH` and these docs disagree, use the safe fallback: `npx --yes -p agentxchain@latest -c "agentxchain <command>"`',
    '',
  ].join('\n');

  writeFileSync(join(root, 'website-v2', 'docs', 'getting-started.mdx'), prereqBlock);
  writeFileSync(join(root, 'website-v2', 'docs', 'quickstart.mdx'), prereqBlock);
  writeFileSync(join(root, 'website-v2', 'docs', 'five-minute-tutorial.mdx'), prereqBlock);
}

after(() => {
  for (const fixture of FIXTURES) {
    rmSync(fixture.root, { recursive: true, force: true });
  }
});

function createFixture({
  version = '2.200.0',
  homepageProof = '24',
  twitterVersion = null,
  linkedinVersion = null,
} = {}) {
  const root = mkdtempSync(join(tmpdir(), 'axc-release-alignment-'));
  const cliScriptsDir = join(root, 'cli', 'scripts');
  const cliLibDir = join(root, 'cli', 'src', 'lib');
  mkdirSync(cliScriptsDir, { recursive: true });
  mkdirSync(cliLibDir, { recursive: true });
  mkdirSync(join(root, 'website-v2', 'docs', 'releases'), { recursive: true });
  mkdirSync(join(root, 'website-v2', 'docs'), { recursive: true });
  mkdirSync(join(root, 'website-v2', 'src', 'pages'), { recursive: true });
  mkdirSync(join(root, 'website-v2', 'static'), { recursive: true });
  mkdirSync(join(root, '.planning', 'MARKETING'), { recursive: true });
  mkdirSync(join(root, '.agentxchain-conformance'), { recursive: true });
  mkdirSync(join(root, 'cli', 'homebrew'), { recursive: true });

  cpSync(CHECK_SCRIPT, join(cliScriptsDir, 'check-release-alignment.mjs'));
  cpSync(ALIGNMENT_LIB, join(cliLibDir, 'release-alignment.js'));
  chmodSync(join(cliScriptsDir, 'check-release-alignment.mjs'), 0o755);

  const releaseDocId = `v${version.replace(/\./g, '-')}`;
  const tarballUrl = `https://registry.npmjs.org/agentxchain/-/agentxchain-${version}.tgz`;
  const twitterTargetVersion = twitterVersion || version;
  const linkedinTargetVersion = linkedinVersion || version;

  writeFileSync(join(root, 'cli', 'package.json'), JSON.stringify({ name: 'agentxchain', version, type: 'module' }, null, 2) + '\n');
  writeFileSync(join(root, 'cli', 'CHANGELOG.md'), `# Changelog\n\n## ${version}\n\nPrepared release.\n\n### Evidence\n\n- 24 tests / 6 suites / 0 failures.\n`);
  writeFileSync(join(root, 'website-v2', 'docs', 'releases', `${releaseDocId}.mdx`), `---\ntitle: "v${version} Release Notes"\n---\n\n# AgentXchain v${version}\n\n## Evidence\n\n- 24 tests / 6 suites / 0 failures.\n`);
  writeFileSync(join(root, 'website-v2', 'docs', 'protocol-implementor-guide.mdx'), `{"version": "${version}"}`);
  writeFileSync(join(root, 'website-v2', 'sidebars.ts'), `export default { docsSidebar: [{ type: 'category', label: 'Release Notes', items: [{ type: 'autogenerated', dirName: 'releases' }] }] };\n`);
  writeFileSync(join(root, 'website-v2', 'src', 'pages', 'index.tsx'), `<div className="hero-badge">v${version}</div>\n<div className="stat-number">${homepageProof}</div>\n<div className="stat-label">Tests / 0 failures</div>\n`);
  writeFileSync(join(root, 'website-v2', 'static', 'llms.txt'), `- ${`/docs/releases/${releaseDocId}`}\n`);
  writeOnboardingDocs(root, version);
  writeFileSync(join(root, '.agentxchain-conformance', 'capabilities.json'), JSON.stringify({ version }, null, 2) + '\n');
  writeFileSync(join(root, '.planning', 'LAUNCH_EVIDENCE_REPORT.md'), `# Launch Evidence Report — AgentXchain v${version}\n\n- 24 tests / 6 suites / 0 failures.\n`);
  writeFileSync(join(root, '.planning', 'SHOW_HN_DRAFT.md'), `# Show HN Draft — AgentXchain v${version}\n\n- 24 tests / 6 suites / 0 failures.\n`);
  writeFileSync(join(root, '.planning', 'MARKETING', 'TWITTER_THREAD.md'), `# Twitter/X Thread — AgentXchain v${twitterTargetVersion}\n\n- 24 tests / 6 suites / 0 failures.\n`);
  writeFileSync(join(root, '.planning', 'MARKETING', 'LINKEDIN_POST.md'), `# LinkedIn Post — AgentXchain v${linkedinTargetVersion}\n\n- 24 tests / 6 suites / 0 failures.\n`);
  writeFileSync(join(root, '.planning', 'MARKETING', 'REDDIT_POSTS.md'), `# Reddit Posts — AgentXchain v${version}\n\n- 24 tests / 6 suites / 0 failures.\n`);
  writeFileSync(join(root, '.planning', 'MARKETING', 'HN_SUBMISSION.md'), `# Hacker News Submission — AgentXchain v${version}\n\n- 24 tests / 6 suites / 0 failures.\n`);
  writeFileSync(join(root, 'cli', 'homebrew', 'agentxchain.rb'), `class Agentxchain < Formula\n  url "${tarballUrl}"\n  sha256 "1111111111111111111111111111111111111111111111111111111111111111"\nend\n`);
  writeFileSync(join(root, 'cli', 'homebrew', 'README.md'), `- version: \`${version}\`\n- source tarball: \`${tarballUrl}\`\n`);

  const fixture = { root };
  FIXTURES.push(fixture);
  return fixture;
}

describe('release alignment manifest', () => {
  it('AT-RAM-001: shared release-alignment module exports scoped surfaces and validates the current repo', () => {
    assert.ok(existsSync(SPEC), 'RELEASE_ALIGNMENT_MANIFEST_SPEC.md must exist');
    assert.ok(RELEASE_ALIGNMENT_SURFACES.length >= 10, 'expected a meaningful release-alignment surface manifest');
    assert.ok(RELEASE_ALIGNMENT_SURFACES.some((surface) => surface.id === 'homepage_proof_stat'));
    assert.ok(RELEASE_ALIGNMENT_SURFACES.some((surface) => surface.id === 'homebrew_formula_url'));
    assert.ok(RELEASE_ALIGNMENT_SURFACES.some((surface) => surface.id === 'onboarding_prereqs'));
    assert.ok(RELEASE_ALIGNMENT_SURFACES.every((surface) => Array.isArray(surface.scopes) && surface.scopes.length > 0));

    const result = validateReleaseAlignment(REPO_ROOT, { scope: RELEASE_ALIGNMENT_SCOPES.CURRENT });
    assert.equal(result.ok, true, JSON.stringify(result.errors, null, 2));
    assert.ok(result.checkedSurfaceIds.includes('show_hn_draft'));
    assert.ok(result.checkedSurfaceIds.includes('linkedin_post'));
    assert.ok(result.checkedSurfaceIds.includes('homebrew_readme'));
    assert.ok(result.checkedSurfaceIds.includes('onboarding_prereqs'));
  });

  it('AT-RAM-002: checker fails prebump scope with actionable surface errors on stale prepared truth', () => {
    const fixture = createFixture({
      homepageProof: '23',
      twitterVersion: '2.199.0',
      linkedinVersion: '2.199.0',
    });
    const result = spawnSync(
      'node',
      ['cli/scripts/check-release-alignment.mjs', '--target-version', '2.200.0', '--scope', 'prebump'],
      { cwd: fixture.root, encoding: 'utf8' },
    );

    assert.equal(result.status, 1);
    assert.match(result.stderr, /\[homepage_proof_stat\]/);
    assert.match(result.stderr, /\[twitter_thread\]/);
    assert.match(result.stderr, /\[linkedin_post\]/);
  });

  it('AT-RAM-005: checker fails prebump scope when onboarding prereq version pins are stale', () => {
    const fixture = createFixture();
    writeOnboardingDocs(fixture.root, '2.199.0');

    const result = spawnSync(
      'node',
      ['cli/scripts/check-release-alignment.mjs', '--target-version', '2.200.0', '--scope', 'prebump'],
      { cwd: fixture.root, encoding: 'utf8' },
    );

    assert.equal(result.status, 1);
    assert.match(result.stderr, /\[onboarding_prereqs\]/);
    assert.match(result.stderr, /website-v2\/docs\/quickstart\.mdx must include: Minimum CLI version: `agentxchain 2\.200\.0` or newer/);
  });

  it('prints a human-readable per-surface report without hiding ready surfaces', () => {
    const fixture = createFixture({
      homepageProof: '23',
      twitterVersion: '2.199.0',
      linkedinVersion: '2.199.0',
    });
    const result = spawnSync(
      'node',
      ['cli/scripts/check-release-alignment.mjs', '--target-version', '2.200.0', '--scope', 'prebump', '--report'],
      { cwd: fixture.root, encoding: 'utf8' },
    );

    assert.equal(result.status, 1);
    assert.match(result.stdout, /Release alignment report for 2\.200\.0 \(prebump,/);
    assert.match(result.stdout, /\[ready\] \(changelog\)/);
    assert.match(result.stdout, /\[needs update\] \(homepage_proof_stat\)/);
    assert.match(result.stdout, /\[needs update\] \(twitter_thread\)/);
    assert.match(result.stdout, /\[needs update\] \(linkedin_post\)/);
    assert.match(result.stdout, /Summary: \d+ ready, \d+ need update\./);
  });

  it('AT-RAM-003: release-bump.sh uses the shared prebump release-alignment checker', () => {
    const source = readFileSync(join(REPO_ROOT, 'cli', 'scripts', 'release-bump.sh'), 'utf8');
    assert.match(source, /check-release-alignment\.mjs/);
    assert.match(source, /--scope prebump/);
  });

  it('AT-RAM-004: release playbook documents manifest-validated manual surfaces and rejects static sitemap prep', () => {
    const playbook = readFileSync(PLAYBOOK, 'utf8');
    assert.match(playbook, /Manifest-driven release alignment/i);
    assert.match(playbook, /Docusaurus generates sitemap output at build time/i);
    assert.doesNotMatch(playbook, /^\s*-\s+`website-v2\/static\/sitemap\.xml`/m);
  });
});
